### ISSUE TITLE
Support for AWS SES provider

### ISSUE THREAD

**Issue by DennisSnijder** [laudspeaker/laudspeaker#101]
## Is your feature request related to a problem?
Not a problem, but would love the have the option to send my mail using AWS SES.

## Describe the solution you'd like
A new mail provider in the UI for AWS SES (https://aws.amazon.com/ses/) should require me to provide an access ID & Secret.

## Describe alternatives you've considered
An alternative would be to use SMTP to send through AWS SES, however the SMTP option seems to be locked for now (not been implemented yet?)

**Comment by abheek9** [comment]
we have  had another request for this!

**Comment by dearroy** [comment]
Would also like to have Amazon SES as an option, we are using Amazon SES for all our other stuff and it's way cheaper than the other options provided.

**Comment by rohitverma007** [comment]
Hi all, would love to build this out, already starting to work on it!
Here's some initial proposals/thoughts.

# AWS SES Integration

Here are the main implementation details that need to be covered:

User Facing:

- During email integration setup, add Amazon SES as an option along with inputs for letting users enter their AWS Access ID + Secret Key, Sender Address, SNS Topic (for email related events, perhaps a tooltip to show how to create and attach an SNS topic to SES). Essentially, update the following page:
    
<img width="1431" alt="emailonboarding" src="https://user-images.githubusercontent.com/3745109/234839343-8db8635f-a3f2-4780-af62-244592bd99cb.png">

    
- Within settings, be able to change the settings for SES integration. Essentially, update the following page:
    
<img width="1440" alt="settingspage" src="https://user-images.githubusercontent.com/3745109/234839373-5bf5ca82-dbd7-4845-9383-0dd0635b204c.png">

    
- Show correct email stats on an active journey page.
    
<img width="1431" alt="statsonactivejourney" src="https://user-images.githubusercontent.com/3745109/234839446-1fd9018b-ca4d-4a8c-8b26-2937e5e35e36.png">

Non-user facing:

- Add all relevant code to be able to store the SES integration settings
- Add all relevant code to be able to actually send out the emails via SES SDK.
- Add all relevant code for monitoring SES emails [opens/ clicked/ bounced etc.]
    - Involves creating a HTTPS subscription to SNS topic via sdk - enables sending of events from SES to SNS to a HTTPS url.
    - Involves creating/handling related events via webhooks

The above is the general overview of what needs to be done. There are likely some details that will be come more clear as feature is implemented.

**Comment by braebo** [comment]
Is there any way around this?  If not, is this being worked on or has it been abandoned?
