### ISSUE TITLE
SSO - Single sign (Github, Gitlab, etc)

### ISSUE THREAD

**Issue by agustif** [laudspeaker/laudspeaker#141]
## Helpful title: I saw a -coming soon-, is this already on the works? Didn't find any issue about it.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/6601142/231759957-9f2cda0f-66f9-4322-b635-2876d7066f94.png">

##Context,
**Link to PRD and short 3 sentences max**

##To Do list
Make SSO work with :
- Github
- Google
- Gitlab

##Story size

##Dates

##Tags

##More Resources

**Comment by agustif** [comment]
Just checked the server codebase, seems we're currently using NestJS + Passport for Auth, so something along the lines of this but for all providers required http://www.passportjs.org/tutorials/google/

Happy to work on this one if anybody else is, seems easy enough to get used to the codebase with a familiar task like auth.

**Comment by mcharawi** [comment]
@agustif sounds good!

**Comment by Dhruwang** [comment]
Would like to work on this one !
