### ISSUE TITLE
Can't add SendGrid account

### ISSUE THREAD

**Issue by jstawski** [laudspeaker/laudspeaker#164]
## Bug description

After correctly adding the Sendgrid API key and the email address I receive a 400 with the message: "There is something wrong with your sendgrid account. Check if your email is verified." I have tried with a key that has full access and one that has partial access to only sending emails. I also tried with the authenticated email configured in Sendgrid as well as with the email I use to login. We use that Sendgrid account in other SaaS solutions without a problem.

## How to reproduce

1. Go to settings
2. Go to Email
3. Select Sendgrid
4. Enter the API Key
5. Enter the Email
6. Click Save

## Environment

- [x] Laudspeaker Cloud
- [ ] self-hosted Laudspeaker, version/commit: _please provide_

**Comment by abheek9** [comment]
thanks looking into the issue now!
