### ISSUE TITLE
One Click Render Deploy Failing

### ISSUE THREAD

**Issue by chandantiwari** [laudspeaker/laudspeaker#169]
## Bug description

Followed all the instructions for One Click deploy on Render. 
All services deployed up and running except Laudspeaker webservice. 

It says following error -
error: required option '--host <name>' not specified

Attached screenshot.
<img width="1388" alt="Screenshot 2023-06-29 at 12 55 23" src="https://github.com/laudspeaker/laudspeaker/assets/4123626/f6ec6b3b-c8a4-4007-814f-4f5b060ee32b">

Am I doing something wrong?

**Comment by sjcotto** [comment]
same error

**Comment by Harshmakadia** [comment]
Same error, Not sure how to fix this.

**Comment by abheek9** [comment]
looking into this now

**Comment by jacobSingh** [comment]
Has this project been abandoned?

**Comment by abheek9** [comment]
No this project is still in active development, we have currently removed support for render deploy
