### ISSUE TITLE
What is the difference between Workflow and Journey?

### ISSUE THREAD

**Issue by devhando** [laudspeaker/laudspeaker#179]
Hi, thanks for this amazing efforts ♥

I have some questions about the implementation of the system:

- I noticed that there're similar two modules (Workflow  and Journey), while Journey module is used in most places, but there's some places where Workflow module is used?

- If I'm right, Workflow module is an old version of Journey, if that is true, why there's new updates and commits to workflow logic?

That's all my questions, 

Thanks.

**Comment by abcx-tech-team** [comment]
I guess they are slowly replacing the workflow module with journey/Flow module, that's why the new journey builder file is JounrneyBuilderV2

**Comment by hyvip-ai** [comment]
I think they are slowly replacing, the WorkFlow module with Journey/Flow module
