### ISSUE TITLE
Unable to Login into the Public cloud Platformat

### ISSUE THREAD

**Issue by Sangeetha-BalaKrishnan** [laudspeaker/laudspeaker#289]
## Bug description

_Please describe._  
_If this affects the front-end, screenshots would be of great help._

## How to reproduce

1. Login into any cloud platform, The auth is going pending
2.
3.

## Environment

- [*
![Uploading Capture.JPG…]()
] Laudspeaker Cloud
- [ ] self-hosted Laudspeaker, version/commit: _please provide_

**Comment by mcharawi** [comment]
Should be fixed.
