### ISSUE TITLE
Live Journey Overview

### ISSUE THREAD

**Issue by abheek9** [laudspeaker/laudspeaker#298]
## Live Journey Overview Tab

##Context,
Right now for our live journeys, we do not have an overview tab, where our users can see a snapshot of how the journey is doing. We want to add a tab called 'Overview' as the first tab of live journeys. (For reference [this](https://www.loom.com/share/e2618b8ee7d24d0ebee65daa8f8f3f23?sid=3a85926c-cb27-401f-8fca-43104dcafd17) a how you get to a live journey)

Here are the design [files](https://www.figma.com/file/aycbaM1DNPJBkWaMuYrjZa/%5BEXT%5D-Live-Journey-Overview?type=design&node-id=0%3A1&mode=design&t=XB6KCwDZefbRkrF9-1)

You can assume you are getting the data you need from specific API calls, and for the conversion rate box, you can use mock data for now. For the definitions of the conversion events, shown on hover, you should assume you get that from an api call when you load the page, for now use mock data.

**Comment by gitstart-laudspeaker** [comment]
Hi @abheek9  , this is the tab layout on the figma design
<img width="496" alt="image" src="https://github.com/GitStartHQ/client-laudspeaker-laud1-laudspeaker/assets/26940294/fd994fcc-28f4-4742-86d1-180b5dfc34a1">

but we will be having something like  this on the current project after the `overview` tab is added
<img width="562" alt="image" src="https://github.com/GitStartHQ/client-laudspeaker-laud1-laudspeaker/assets/26940294/bd19afdc-2351-4f3c-bf07-1bf42f8a75f3">


Are we sticking to the tab style that we have on the current project or we switch it up to use the design in Figma?
