### ISSUE TITLE
Your website has a Javascript error and it is impossible to view contact details or get in touch!!

### ISSUE THREAD

**Issue by randomm** [laudspeaker/laudspeaker#431]
Hi,

we are interested in switching over to using your product, but your website has an error making it impossible to proceed to contact you guys. If you see this, please get in touch with me here.

<img width="1360" alt="Screenshot 2024-05-07 at 10 50 39" src="https://github.com/laudspeaker/laudspeaker/assets/259547/f2f7d172-0196-473c-9dfc-c8c8f1965877">

Thanks!

Janni

**Comment by abheek9** [comment]
hey Janni, i sent you an email, if you didnt get it you can email me at hey [at] laudspeaker [dot] com

- we are updating our site apologies for the confusion!
