### ISSUE TITLE
Possible bug, sqlQuery not using the trimed date value of miliseconds 

### ISSUE THREAD

**Issue by Eslam3bed** [laudspeaker/laudspeaker#452]
### Bug description:
The `formattedTimeAfter` var is not used, instead, the plain date `timeAfter` var value is injected in the `sqlQuery`!
 
#### Reference where the issue is:

https://github.com/laudspeaker/laudspeaker/blob/7e4ccdda497a1adb7b5945cbf75ffe64383a64ae/packages/server/src/api/customers/customers.service.ts#L4823

**Comment by MoustafaEid** [comment]
Nice find, thank you @Eslam3bed!
