### ISSUE TITLE
Can not create/import users in cloud version

### ISSUE THREAD

**Issue by MrSnoozles** [laudspeaker/laudspeaker#529]
## Bug description

Hi, I signed up for Laudspeaker, but am unable to start. I wanted to create my first user, but the button is disabled.
![image](https://github.com/user-attachments/assets/88800cc3-03b5-435b-9328-49570374a41f)

Next, I wanted to import a test user via CSV instead, but when uploading my `users.csv` file I get a message `File must have .csv extension`

![image](https://github.com/user-attachments/assets/271e4286-2718-44f3-92dc-012e053b1436)

The journey builder looks really great, but having issues this early on doesn't give a lot of trust in the product.

## Environment

- [x] Laudspeaker Cloud
- [ ] self-hosted Laudspeaker, version/commit: _please provide_

**Comment by abheek9** [comment]
Hey you need to set up the user schema first before you can create or upload users. This is shown on the home page, and is covered in the docs here - https://laudspeaker.com/docs/getting-started/setting-up-schema-and-channels

In any case we will add a warning around the button to make that more clear!

**Comment by MrSnoozles** [comment]
@abheek9 Thanks for the quick response.

The problem seems to be, that the primary key can not be saved. I added a recording for reference:

![laudspeaker](https://github.com/user-attachments/assets/16001d2b-e6ec-43cc-9ec8-3532190eedc5)

Also, there are a few, probably easy to fix, bugs that made the first impression worse for me:

**Website:**
- on the pricing page, clicking "Get started now" does nothing as it's just an anchor link to the top of the page
- in the footer menu, the "Careers" entry links to the old website
- when signing up I could not choose a plan. Instead it automatically chose the "Startup" plan, but for $75/month - the website states $300/month. Also I do not find my subscription in the app.

**App:**
1. "Data" in the menu is toggable but does not open anything. I guess this might come when there are some users, but after onboarding it looks like a bug
2. In several places you have "comming soon" written, which is a typo (should be "coming soon")
3. (As mentioned in my first post) uploading a *.csv and getting the error "File must have *.csv extension" does not build a lot of trust in the more complex logic.

**Comment by MrSnoozles** [comment]
Turns out the primary key  can't be named `name`. When I change it to something else it works.

@abheek9 The software is incredible, but needs a bit more polishing and a more active community. Are you interested in people submitting pull requests?

Also I have a few questions, what's the best place to ask them?
1. Is there a list of "expected field names"? E.g. for push notifications to work the user has to have a `androidDeviceToken` or `iosDeviceToken` field. That's not a system field though. Are there more fields like this?
2. Is there a way to handle messages in multiple languages without having to duplicate the flows for every language?
3. Is a PostHog event provider still  is coming soon?
4. Can events be collected and summarized in one message? Example: A post gets 8 likes. I want to send a push message saying "MrSnoozles and 7 others like your post". Is there some documentation how to do this?

Keep up the good work, this might become very successful with a little more polishing.

**Comment by abheek9** [comment]
Thanks for the feedback @MrSnoozles , yes we need to fix up and polish a few more things! The best way to chat is through our slack link - here it : [is](https://join.slack.com/t/laudspeakerusers/shared_invite/zt-2vn19c53k-wNiaTmLyT~rFUsjKN_NdUg)

1. You are right we do have a list of reserved fields that can't be used in the schema - we will add to our docs, and make clearer in the app
2. We don't have a translation function explicitly but we have had some users use liquid templating with a user langauge field to do this, eg: 
{% assign language = "spanish" %} {# Change this to "french" or "english" to test other languages #}

{% if language == "spanish" %}
  ¡Hola! ¿Cómo estás? Este es un mensaje en español.
{% elsif language == "french" %}
  Bonjour ! Comment ça va ? Ceci est un message en français.
{% else %}
  Hello! How are you? This is a message in English.
{% endif %}
3. You can actually use PostHog today, with their data pipeline feature, you would need to transform and then set our endpoint as the destination to fit our event schema - we have a few users doing this (we are working on a blog post to show how)
4. There are a few ways of doing this in Laudspeaker today - happy to walk you through how in a call, if you book a time via the calender link on the github readme

**Comment by MrSnoozles** [comment]
@abheek9 Thanks for the new Slack link. The link on the homepage and the Github readme is not working anymore (try it in a private browser window)

**Comment by abheek9** [comment]
apologies will fix the links , here is a [link to chat with our team](https://cal.com/laudspeaker-mahamad/20min-set-up?month=2024-12&date=2024-12-03), would love to learn how we could be used by you guys
