### ISSUE TITLE
Slack link on homepage is broken

### ISSUE THREAD

**Issue by ottman** [laudspeaker/laudspeaker#54]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1. Go to homepage
2. Tap join community
3. Broken

## Environment

- [ ] Laudspeaker Cloud
- [ ] self-hosted Laudspeaker, version/commit: _please provide_

## Additional context

![image](https://user-images.githubusercontent.com/1923016/207107328-ad414b57-0ffd-4a71-8fcc-f04138b3dc98.png)

**Comment by ottman** [comment]
How do we get in touch with you all. We would like to set a call.

**Comment by abheek9** [comment]
thanks for the report - updated the links. To get in touch you can email me hey at laudspeaker dot com. You can also directly book time with me [here](https://cal.com/laudspeaker/30min)
