### ISSUE TITLE
One Click deploy on Render fail - 

### ISSUE THREAD

**Issue by send2cloud** [laudspeaker/laudspeaker#92]
I setup new account. on render.com, added credit card as render said render.yaml required creditcard.
gave it a name, "docker deploy" was preselected in dropdown.

ERROR:
_A render.yaml file was found, but there was an issue.

web."laudspeaker".envVarGroups
env var group linkage depends on non-existent group: laudspeaker_

**Comment by send2cloud** [comment]
here was the rest of the error:
services:
  - type: web
    name: laudspeaker
    healthCheckPath: /login
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - fromGroup: laudspeaker
      - key: PORT
        value: 80
      - key: SYNCHRONIZE
        value: true
      - key: JWT_KEY
        generateValue: true
      - key: JWT_EXPIRES
        value: 365d
      - key: MONGOOSE_URL
        fromService:
          type: pserv
          name: mongo
          property: hostport
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: clickhouse
          property: hostport
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laudspeaker
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laudspeaker
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: laudspeaker-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: laudspeaker-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: laudspeaker-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: laudspeaker-db
          property: database
  - type: redis
    name: laudspeaker
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: pserv
    name: clickhouse
    env: docker
    dockerfilePath: ./Dockerfile.clickhouse
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
  - type: pserv
    name: mongo
    env: docker
    dockerfilePath: ./Dockerfile.mongo
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
databases:
- name: laudspeaker-db

**Comment by abheek9** [comment]
hey @send2cloud! thanks for the issue, we should have had a clearer link to the [docs](https://laudspeaker.com/docs/guides/deploy/options) for this. there should be an env group laudspeaker
