### ISSUE TITLE
How could I create a new Communication Provider?

### ISSUE THREAD

**Issue by pavei** [laudspeaker/laudspeaker#96]
## Is your feature request related to a problem?

I have a API for WhatsApp and I would like to create a provider to use laudspeaker. Is there a Doc to create a custom provider?

_Please describe._

**Comment by mcharawi** [comment]
Hey @pavei , thanks for opening this issue. Could you please describe your WhatsApp API in more detail? Are you using Twilio, the native WhatsApp API, or something else? There are a few things that you will need to implement if you want to create a new provider. You will need templates for you messages, user settings to set the necessary parameters to communicate with your API, and authenticated webhooks for message events, such as Sent/Delivered/Read. You can start by joining our [Slack](https://laudspeakerusers.slack.com/ssb/redirect) and we can help you get set up with local development.
